spring:
  application:
    name: evcs
  profiles:
    include:
      - private
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:uploads/
  restart:
    enabled: false
  livereload:
    enabled: false

server:
  port: 80

servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: VARCHAR
  mapper-locations: classpath:mapper/*.xml

  type-aliases-package: 
    com.example.evcs.admin.carInfo.model.vo , com.example.evcs.admin.carInfo.model.dto, com.example.evcs.admin.rentCarInfo.model.dto, com.example.evcs.admin.rentCarInfo.model.vo 
    com.example.evcs.event.model.vo, com.example.evcs.event.model.dto

logging:
  level:
    root: info
    org.apache.ibatis: DEBUG
    java.sql: DEBUG
    jdbc.sqlonly: DEBUG
    jdbc.resultset: DEBUG
    jdbc.audit: DEBUG
