jwt:
  secret: H7oIaBujRo6fA/a0wdk09iY6STECQZbemMj8bcs5xBMzd0IYxzT+hNQd+fgXvsyz3qHF3DIwuYXUE9m7w5tkDw==

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@112.221.156.34:12345:xe
    username: KH07_KYS
    password: KH1234		    

  mail:
    username: kysman2580@gmail.com
    password: hxjlsdyhsuutrdii